import Zcash.Circuits.Integration.FixedColumns
import Zcash.Common.RelationWitness
import Zcash.Snark.Keygen.Lagrange
import Zcash.Snark.Soundness.Canonical.PermutationSemantics

/-!
# σ-column commitment provenance

The verifying key's common-permutation commitments are the Lagrange commitments of the
keygen σ columns, while the multiopen extractor returns augmented monomial-basis
openings for the very same commitment slots. This module crosses that representation
boundary exactly as `Integration/FixedColumns` does for the fixed family: a routed
decoded σ polynomial is the polynomial interpolating its keygen σ rows, or the two
openings compute a nontrivial relation among the augmented URS generators.

The keygen side speaks a third spelling — `keygenSigmaColumn`, the interpolation of the
replayed cell names. `instanceRowPolynomial_eq_keygenSigmaColumn` closes that gap: both
are Lagrange interpolations over the same `ω`-power nodes, so a σ-row list whose entries
are the replayed names interpolates to the generated column. Composing the two gives the
`hcolumns` premise of `ResolverPermutationCycle.ofKeygenColumns` up to the retained
relation branch: decoded σ polynomial = generated keygen σ column, or a computed
discrete-log relation.

Unlike the fixed family, query coverage needs no coherence field: the verifier opens
every σ commitment unconditionally (`assembleQueries_permCommon_query`).
-/

namespace Zcash.Snark

open Zcash.Arithmetic (derivedUrsGLagrange derivedUrsGLagrange_length omegaOf)

open Halo2 Polynomial

set_option maxHeartbeats 20000

variable {G : Type} [AddCommGroup G] [Module Fp G]
  [DecidableEq G] [Inhabited G]

/-- The dense σ rows generated by a closed top-level circuit, in global
permutation-column order. -/
def topLevelPermutationRows
    {Config : Type} {PublicInput : TypeMap}
    [ProvableType PublicInput]
    (top : TopLevelCircuit Fp Config PublicInput)
    (column : ℕ) : List Fp :=
  (Keygen.permPolysOf top.domainExponent top.constraintSystem
    (top.operations)).getD column []

/-- The common-permutation commitment emitted by keygen at a natural column
index. Keeping this projection opaque prevents coherence interfaces from
reducing the full circuit compiler merely to elaborate their types. -/
def topLevelPermutationCommitment
    {Config : Type} {PublicInput : TypeMap}
    [ProvableType PublicInput]
    (top : TopLevelCircuit Fp Config PublicInput)
    (urs : URS G) (column : ℕ) : G :=
  (top.permutationCommitments urs).getD column 0

/-- Number of permutation columns emitted by the keygen compiler. -/
def topLevelPermutationColumnCount
    {Config : Type} {PublicInput : TypeMap}
    [ProvableType PublicInput]
    (top : TopLevelCircuit Fp Config PublicInput) : ℕ :=
  (Keygen.permColsOf top.constraintSystem).length

/-- Total natural-number projection of a common-permutation commitment.
The in-range theorem below reconnects it to the verifier's `Fin`-indexed
interface without making every circuit-coherence record reduce its derived
shape while elaborating. -/
def permutationCommonCommitmentAt
    {shape : Shape} {F G : Type} [Inhabited G]
    (vk : VerifyingKey shape F G) (column : ℕ) : G :=
  if hcolumn : column < shape.numPermutationColumns then
    vk.permutationCommonCommitment ⟨column, hcolumn⟩
  else default

@[simp]
theorem permutationCommonCommitmentAt_of_lt
    {shape : Shape} {F G : Type} [Inhabited G]
    (vk : VerifyingKey shape F G) (column : ℕ)
    (hcolumn : column < shape.numPermutationColumns) :
    permutationCommonCommitmentAt vk column =
      vk.permutationCommonCommitment ⟨column, hcolumn⟩ := by
  simp [permutationCommonCommitmentAt, hcolumn]

/-- The setup facts needed by prefix-based Lagrange commitments. -/
structure LagrangePrefixSetup (urs : URS G) : Prop where
  length_eq :
    (derivedUrsGLagrange urs).length = 2 ^ urs.k
  generator_eq :
    ∀ i : Fin (2 ^ urs.k),
      (i : ℕ) < (derivedUrsGLagrange urs).length →
        (derivedUrsGLagrange urs).getD (i : ℕ) 0 =
          commit urs (polynomialCoefficients (2 ^ urs.k)
            (rowPolynomial (omegaOf urs.k)
              (Pi.single i (1 : Fp))))

namespace LagrangePrefixSetup

/-- The symbolic FFT correctness theorem supplies the complete Lagrange-prefix
setup for every supported Halo 2 domain. -/
def ofDerived (urs : URS G) (hk : urs.k ≤ 32) :
    LagrangePrefixSetup urs where
  length_eq := derivedUrsGLagrange_length urs
  generator_eq :=
    Keygen.ofPrefix_setup_of_closed urs hk
      (Keygen.derivedUrsGLagrange_generator_eq urs hk)

end LagrangePrefixSetup

/--
Nat-indexed permutation commitment provenance over compiler snapshots.
Keeping the small count, rows, and commitment projections explicit prevents
record elaboration from reducing a complete `TopLevelCircuit`.
-/
structure PermutationCommitmentCoherence
    (urs : URS G) (numColumns : ℕ)
    (rows : ℕ → List Fp) (commitments : ℕ → G) where
  key :
    LagrangeCommitmentKey urs (omegaOf urs.k)
  commitment :
    ∀ column : ℕ,
      column < numColumns →
      commitments column =
        key.commitInstance
          (rows column) 1

namespace PermutationCommitmentCoherence

omit [DecidableEq G] in
/--
The keygen permutation commitment at every in-range column is the prefix-key
commitment of the row vector emitted for that column.

This is deliberately a direct theorem rather than a constructor returning a
circuit-specialized record: the latter makes Lean normalize the entire circuit
while elaborating its result type, whereas this compiler-native statement stays
small and generic.
-/
theorem commitment_ofKeygen
    {Config : Type} {PublicInput : TypeMap}
    [ProvableType PublicInput]
    (top : TopLevelCircuit Fp Config PublicInput)
    (urs : URS G)
    (hk : top.domainExponent = urs.k)
    (setup : LagrangePrefixSetup urs)
    (column : ℕ)
    (hcolumn : column < topLevelPermutationColumnCount top) :
    topLevelPermutationCommitment top urs column =
      (LagrangeCommitmentKey.ofPrefix urs
        (omegaOf urs.k)
        (derivedUrsGLagrange urs)
        setup.generator_eq).commitInstance
          (topLevelPermutationRows top column) 1 := by
  unfold topLevelPermutationColumnCount at hcolumn
  unfold topLevelPermutationCommitment
  have hcommit :=
    Keygen.permutationCommitmentsOf_getD_eq_commitInstance
      urs top.constraintSystem (top.operations)
      setup.length_eq setup.generator_eq
      column hcolumn
  unfold TopLevelCircuit.permutationCommitments topLevelPermutationRows
  rw [hk]
  exact hcommit

end PermutationCommitmentCoherence

/-- A σ-row list whose entries are the replayed permutation's cell names interpolates to
the generated keygen σ column: both sides are Lagrange interpolations over the same
`ω`-power nodes, so the polynomials agree definitionally once the values do. -/
theorem instanceRowPolynomial_eq_keygenSigmaColumn
    {nc n : ℕ} {width : ℕ → ℕ}
    (omega delta : Fp) (chunkLen : ℕ)
    (sigma : Equiv.Perm (ChunkCell nc n width))
    (chunk : Fin nc) (column : Fin (width chunk))
    (rows : List Fp)
    (hval : ∀ i : Fin n, rows.getD (i : ℕ) 0 =
      chunkRowName omega delta chunkLen
        (sigma ⟨chunk, i, column⟩).1
        (sigma ⟨chunk, i, column⟩).2.1
        (sigma ⟨chunk, i, column⟩).2.2) :
    instanceRowPolynomial n omega rows =
      keygenSigmaColumn omega delta chunkLen sigma chunk column := by
  unfold instanceRowPolynomial rowPolynomial keygenSigmaColumn zeroPaddedRows
  exact congrArg _ (funext fun i => hval i)

namespace CanonicalMemberConstraintRelation

variable
    {shape : Shape}
    {urs : URS G} {hk : shape.k = urs.k}
    {vk : VerifyingKey shape Fp G}
    {instanceCommitment : Fin shape.numProofs → ℕ → G}
    {ps : ProofString shape Fp G}
    {ch : Challenges shape.k Fp}
    {pU pW : Fp} {a : Fin (2 ^ urs.k) → Fp}
    {batchOpenings :
      OpenedBatchOpenings urs (evalVector urs.k ch.x3)
        (x4BatchCommitments
          (instanceCommitment := instanceCommitment)
          urs hk vk ps ch)
        (x4BatchEvals
          (instanceCommitment := instanceCommitment)
          vk ps ch)
        a pU pW}
    {memberDecode : ∀ i (hi : i <
        deployedX4PairCount
          (instanceCommitment := instanceCommitment)
          vk ps ch),
      OpenedMemberDecode
        (instanceCommitment := instanceCommitment)
        urs hk vk ps ch batchOpenings i hi}
    {hblinding : vk.blindingFactors < vk.n}
    {y : Fp} {hpoly : Polynomial Fp} {deg : ℕ}

/--
A canonically routed σ-column opening is the polynomial interpolating its keygen σ
rows, or it exhibits an augmented commitment relation.

`hcommit` is the circuit-keygen side of the boundary: the common-permutation commitment
stored in the derived VK is the Lagrange commitment to `rows` with Halo 2's default
blind `1`. It is independent of the proof and can be established once for the generic
`TopLevelCircuit.toVerifierKey` construction. Query coverage is unconditional: every σ
commitment is opened by the assembled queries.
-/
noncomputable def permCommon_eq_rowPolynomial_or_relation
    (relation : CanonicalMemberConstraintRelation
      urs hk vk instanceCommitment ps ch pU pW a
      batchOpenings memberDecode hblinding y hpoly deg)
    (c : Fin shape.numPermutationColumns)
    (key : LagrangeCommitmentKey urs vk.omega)
    (rows : List Fp)
    (hcommit :
      vk.permutationCommonCommitment c =
        key.commitInstance rows 1)
    (hrows : Function.Injective
      fun i : Fin (2 ^ urs.k) => vk.omega ^ (i : ℕ)) :
    relation.polynomial (.permCommon (c : ℕ)) =
        instanceRowPolynomial (2 ^ urs.k) vk.omega rows ⊕'
      NontrivialRelation (F := Fp) urs.g urs.u urs.w := by
  classical
  have hquery := assembleQueries_permCommon_query vk instanceCommitment ps ch c
  let q := Classical.choose hquery
  have hq : q ∈ assembleQueries vk instanceCommitment ps ch :=
    (Classical.choose_spec hquery).1
  have hqid : q.commId = _ := (Classical.choose_spec hquery).2
  have routed :=
    assembledQueryMemberRoute_faithful
      (instanceCommitment := instanceCommitment)
      vk ps ch relation.groupingCount relation.noDuplicateQueries q hq
  have routedCommon :
      relation.route (.permCommon (c : ℕ)) = some routed.slot := by
    rw [← hqid]
    exact routed.route_eq
  have hid :
      (deployedSetCommIds (instanceCommitment := instanceCommitment)
        vk ps ch routed.slot.setIndex).getD
          (routed.slot.memberIndex : ℕ) .vanishingH =
        .permCommon (c : ℕ) := by
    apply assembledQueryMemberRoute_id
      (instanceCommitment := instanceCommitment)
      vk ps ch relation.groupingCount relation.noDuplicateQueries
      (.permCommon (c : ℕ)) routed.slot
    simpa [CanonicalMemberConstraintRelation.route] using routedCommon
  have href :=
    deployedMemberRef_eq_permCommonCommitment
      (instanceCommitment := instanceCommitment)
      vk ps ch relation.groupingCount routed.slot c hid
  let decoded :=
    memberDecode routed.slot.setIndex routed.slot.setIndex_lt
  have hopen :
      commit urs (decoded.cols routed.slot.memberIndex) +
          decoded.uComp routed.slot.memberIndex • urs.u +
          decoded.wComp routed.slot.memberIndex • urs.w =
        key.commitInstance rows 1 := by
    calc
      commit urs (decoded.cols routed.slot.memberIndex) +
            decoded.uComp routed.slot.memberIndex • urs.u +
            decoded.wComp routed.slot.memberIndex • urs.w =
          ((deployedSetQueries
              (instanceCommitment := instanceCommitment)
              vk ps ch routed.slot.setIndex).getD
            (routed.slot.memberIndex : ℕ) (.point 0, [])).1.eval
              ⟨shape.k, hk ▸ urs.g, urs.w, urs.u⟩ :=
        decoded.commitment routed.slot.memberIndex
      _ = vk.permutationCommonCommitment c := by
        rw [href]
        rfl
      _ = key.commitInstance rows 1 := hcommit
  have hbound :=
    coeffsToPoly_eq_instanceRowPolynomial_or_relation
      key rows 1
      (decoded.cols routed.slot.memberIndex)
      (decoded.uComp routed.slot.memberIndex)
      (decoded.wComp routed.slot.memberIndex)
      hrows hopen
  refine bindOrRelationWitness hbound fun heq => ?_
  rw [CanonicalMemberConstraintRelation.polynomial,
    decodedPolynomialResolver, routedCommon]
  exact heq

/--
**The σ-column identification.** A canonically routed common-permutation opening is the
generated keygen σ column — the `hcolumns` premise of
`ResolverPermutationCycle.ofKeygenColumns` — or it exhibits an augmented commitment
relation. `hval` is the keygen-side name fact: the committed σ rows are the replayed
permutation's cell names.
-/
noncomputable def permCommon_eq_keygenSigmaColumn_or_relation
    {nc : ℕ} {width : ℕ → ℕ}
    (relation : CanonicalMemberConstraintRelation
      urs hk vk instanceCommitment ps ch pU pW a
      batchOpenings memberDecode hblinding y hpoly deg)
    (c : Fin shape.numPermutationColumns)
    (key : LagrangeCommitmentKey urs vk.omega)
    (rows : List Fp)
    (hcommit :
      vk.permutationCommonCommitment c =
        key.commitInstance rows 1)
    (hrows : Function.Injective
      fun i : Fin (2 ^ urs.k) => vk.omega ^ (i : ℕ))
    (sigma : Equiv.Perm (ChunkCell nc (2 ^ urs.k) width))
    (chunk : Fin nc) (column : Fin (width chunk))
    (hval : ∀ i : Fin (2 ^ urs.k), rows.getD (i : ℕ) 0 =
      chunkRowName vk.omega vk.delta vk.chunkLen
        (sigma ⟨chunk, i, column⟩).1
        (sigma ⟨chunk, i, column⟩).2.1
        (sigma ⟨chunk, i, column⟩).2.2) :
    relation.polynomial (.permCommon (c : ℕ)) =
        keygenSigmaColumn vk.omega vk.delta vk.chunkLen sigma chunk column ⊕'
      NontrivialRelation (F := Fp) urs.g urs.u urs.w :=
  bindOrRelationWitness
    (relation.permCommon_eq_rowPolynomial_or_relation c key rows hcommit hrows)
    fun heq => heq.trans
      (instanceRowPolynomial_eq_keygenSigmaColumn
        vk.omega vk.delta vk.chunkLen sigma chunk column rows hval)

end CanonicalMemberConstraintRelation

omit [AddCommGroup G] [Module Fp G] [DecidableEq G] [Inhabited G] in
/-- The σ side of a resolver permutation pair is the resolver at the chunk entry's
common-polynomial index. -/
theorem resolverPermutationPairs_getElem_snd
    {shape : Shape} (vk : VerifyingKey shape Fp G)
    (poly : CommitmentId → Polynomial Fp) (p : Fin shape.numProofs)
    (c j : ℕ) (hj : j < (vk.permutationChunks.getD c []).length) :
    (ResolverPermutationPairs vk poly p c)[j]'
        (by simpa [ResolverPermutationPairs, permutationChunkPairsOfResolver] using hj) =
      (permutationColumnPolynomialOfResolver vk poly p
          ((vk.permutationChunks.getD c [])[j]).1,
        poly (.permCommon ((vk.permutationChunks.getD c [])[j]).2)) := by
  simp [ResolverPermutationPairs, permutationChunkPairsOfResolver]

namespace CanonicalMemberConstraintRelation

variable
    {shape : Shape}
    {urs : URS G} {hk : shape.k = urs.k}
    {vk : VerifyingKey shape Fp G}
    {instanceCommitment : Fin shape.numProofs → ℕ → G}
    {ps : ProofString shape Fp G}
    {ch : Challenges shape.k Fp}
    {pU pW : Fp} {a : Fin (2 ^ urs.k) → Fp}
    {batchOpenings :
      OpenedBatchOpenings urs (evalVector urs.k ch.x3)
        (x4BatchCommitments
          (instanceCommitment := instanceCommitment)
          urs hk vk ps ch)
        (x4BatchEvals
          (instanceCommitment := instanceCommitment)
          vk ps ch)
        a pU pW}
    {memberDecode : ∀ i (hi : i <
        deployedX4PairCount
          (instanceCommitment := instanceCommitment)
          vk ps ch),
      OpenedMemberDecode
        (instanceCommitment := instanceCommitment)
        urs hk vk ps ch batchOpenings i hi}
    {hblinding : vk.blindingFactors < vk.n}
    {y : Fp} {hpoly : Polynomial Fp} {deg : ℕ}

/--
`hcolumns` at one chunk entry, up to the retained relation branch: the σ side of the
resolver's permutation pair is the generated keygen σ column. The routing premises
(`hj`, `hlt`, `hidx`) are chunk-layout facts of the concrete verifying key; `hcommit`
and `hval` are the keygen-side commitment and name facts.
-/
noncomputable def resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation
    {nc : ℕ} {width : ℕ → ℕ}
    (relation : CanonicalMemberConstraintRelation
      urs hk vk instanceCommitment ps ch pU pW a
      batchOpenings memberDecode hblinding y hpoly deg)
    (p : Fin shape.numProofs) (cIdx j : ℕ)
    (hj : j < (vk.permutationChunks.getD cIdx []).length)
    (c : Fin shape.numPermutationColumns)
    (hidx : ((vk.permutationChunks.getD cIdx [])[j]).2 = (c : ℕ))
    (key : LagrangeCommitmentKey urs vk.omega)
    (rows : List Fp)
    (hcommit :
      vk.permutationCommonCommitment c =
        key.commitInstance rows 1)
    (hrows : Function.Injective
      fun i : Fin (2 ^ urs.k) => vk.omega ^ (i : ℕ))
    (sigma : Equiv.Perm (ChunkCell nc (2 ^ urs.k) width))
    (chunk : Fin nc) (column : Fin (width chunk))
    (hval : ∀ i : Fin (2 ^ urs.k), rows.getD (i : ℕ) 0 =
      chunkRowName vk.omega vk.delta vk.chunkLen
        (sigma ⟨chunk, i, column⟩).1
        (sigma ⟨chunk, i, column⟩).2.1
        (sigma ⟨chunk, i, column⟩).2.2) :
    ((ResolverPermutationPairs vk relation.polynomial p cIdx)[j]'
        (by simpa [ResolverPermutationPairs, permutationChunkPairsOfResolver] using hj)).2 =
        keygenSigmaColumn vk.omega vk.delta vk.chunkLen sigma chunk column ⊕'
      NontrivialRelation (F := Fp) urs.g urs.u urs.w := by
  refine bindOrRelationWitness
    (relation.permCommon_eq_keygenSigmaColumn_or_relation
      c key rows hcommit hrows sigma chunk column hval) fun heq => ?_
  rw [resolverPermutationPairs_getElem_snd vk relation.polynomial p cIdx j hj]
  rw [← heq, hidx]

/--
Size-transported form of
`resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation`.

Circuit compilers naturally index σ rows by their own domain-size name, while
the commitment extractor names the same size as `2 ^ urs.k`. Localizing that
propositional equality here keeps concrete circuit permutations free of
dependent casts.
-/
noncomputable def resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation_of_size
    {nc n : ℕ} {width : ℕ → ℕ}
    (relation : CanonicalMemberConstraintRelation
      urs hk vk instanceCommitment ps ch pU pW a
      batchOpenings memberDecode hblinding y hpoly deg)
    (p : Fin shape.numProofs) (cIdx j : ℕ)
    (hj : j < (vk.permutationChunks.getD cIdx []).length)
    (c : Fin shape.numPermutationColumns)
    (hidx : ((vk.permutationChunks.getD cIdx [])[j]).2 = (c : ℕ))
    (key : LagrangeCommitmentKey urs vk.omega)
    (rows : List Fp)
    (hcommit :
      vk.permutationCommonCommitment c =
        key.commitInstance rows 1)
    (hrows : Function.Injective
      fun i : Fin (2 ^ urs.k) => vk.omega ^ (i : ℕ))
    (hn : n = 2 ^ urs.k)
    (sigma : Equiv.Perm (ChunkCell nc n width))
    (chunk : Fin nc) (column : Fin (width chunk))
    (hval : ∀ i : Fin n, rows.getD (i : ℕ) 0 =
      chunkRowName vk.omega vk.delta vk.chunkLen
        (sigma ⟨chunk, i, column⟩).1
        (sigma ⟨chunk, i, column⟩).2.1
        (sigma ⟨chunk, i, column⟩).2.2) :
    ((ResolverPermutationPairs vk relation.polynomial p cIdx)[j]'
        (by simpa [ResolverPermutationPairs,
          permutationChunkPairsOfResolver] using hj)).2 =
        keygenSigmaColumn vk.omega vk.delta vk.chunkLen sigma chunk column ⊕'
      NontrivialRelation (F := Fp) urs.g urs.u urs.w := by
  subst n
  exact relation.resolverPermutationPairs_snd_eq_keygenSigmaColumn_or_relation
    p cIdx j hj c hidx key rows hcommit hrows sigma chunk column hval

end CanonicalMemberConstraintRelation

end Zcash.Snark
