import Mathlib
import Zcash.Arithmetic.Msm
import Zcash.Snark.Fingerprint.SchwartzZippel
import Zcash.Snark.Verifier.Assemble

/-!
# The fingerprint match

The cross-check that validates the Lean assembly against the deployed Rust verifier (in place of a
line-by-line translation proof): run the deployed verifier on a proof, capturing its assembled MSM and
the challenges it drew; run the Lean `assemble` on the same proof string and challenges; and compare
the two MSMs. A match means the two assembled MSMs agree coefficient-for-coefficient on this proof —
not merely as evaluated group elements.

This module provides the match's logical content:

* `MsmMatch` — coefficient-for-coefficient equality, with the commitment term lists compared up
  to reordering; `msmMatch_eval` shows a match implies equal evaluations. Both sides use the
  captured proof's own commitments as bases, so the match is a comparison of `F_p` scalars.
* `fingerprint_match_random_eval_sound` — soundness of the cheaper random-evaluation match: a
  nonzero coefficient difference evades a uniformly random evaluation with probability `≤ d / p`
  (Schwartz–Zippel). Stated for an abstract polynomial, not `assemble`'s actual coefficients, so
  it is not yet a Lean link; the `native_decide` fixture match is what establishes agreement, on
  one captured proof, full stop.
* `gScalars_card` — the structural cross-check: the assembled MSM carries `2 ^ k` URS-generator
  coefficients, matching the captured Orchard fingerprint's `2 ^ 11 = 2048`.

## What remains external

The Rust capture lives in upstream draft PRs: the capture APIs (`FingerprintStrategy`,
`ChallengeRecorder`, `MSM::fingerprint_terms`) in
[zcash/halo2#914](https://github.com/zcash/halo2/pull/914), and the capture test in
[zcash/orchard#531](https://github.com/zcash/orchard/pull/531). The captured fixture itself — the
`2048` g-scalars, `100` commitment terms, `22` challenges, and the `VerifyingKey` — is loaded in
`Fixtures/SingleAction/Fixture.lean` (auto-generated by `dump_vesta_lean_fixture`), and `Fixture.fingerprint_matches`
runs the decidable comparison `MsmMatch (assemble vk ps ch) capturedMsm` by `native_decide` over
actual Vesta points. The generator emits every distinct affine coordinate, validates it on
`Vesta.curve`, and supplies the complete Halo2 URS; `capturedMsm_eval_eq_zero` then computes the
captured MSM to the identity and `assembledMsm_eval_eq_zero` transfers that result to Lean's
assembly. Rust key generation, the comparison against Orchard's canonical Post-NU6.3
`PinnedVerificationKey`, and Halo2's pinned-key serialization/Blake2b derivation remain the
fixture-generation boundary rather than being reimplemented in Lean.
-/

namespace Zcash.Snark

open Zcash.Arithmetic (Msm scalarFieldOrder)

/-- Two MSMs match iff their `g`/`w`/`u` coefficients are equal and their `other` term lists agree
up to reordering (`List.Perm`) — term order is only a serialization artifact of how each assembler
appends, and the term sum is order-independent (`msmMatch_eval`). -/
def MsmMatch {k : ℕ} {F G : Type*} (m₁ m₂ : Msm k F G) : Prop :=
  m₁.gScalars = m₂.gScalars ∧ m₁.wScalar = m₂.wScalar ∧ m₁.uScalar = m₂.uScalar ∧ m₁.other.Perm m₂.other

/-- **The fingerprint match implies equal evaluations.** Matching MSMs denote the same group
element under any URS — the term sum is order-independent — so the deployed accept check
(`eval = identity`) transfers. -/
theorem msmMatch_eval {F G : Type*} [Field F] [AddCommGroup G] [Module F G] (urs : URS G)
    {m₁ m₂ : Msm urs.k F G} (h : MsmMatch m₁ m₂) : m₁.eval urs = m₂.eval urs := by
  obtain ⟨hg, hw, hu, ho⟩ := h
  unfold Msm.eval
  rw [hg, hw, hu, (ho.map (fun t => t.1 • t.2)).sum_eq]

/-- Matching concrete `ZMod` MSMs have equal executable evaluations. Unlike `msmMatch_eval`, this
uses canonical-natural scalar multiplication and therefore needs no group-order or module
assumption; it is the transfer theorem used by the concrete Vesta fixtures. -/
theorem msmMatch_evalNat {p : ℕ} {G : Type*} [AddCommGroup G] (urs : URS G)
    {m₁ m₂ : Msm urs.k (ZMod p) G} (h : MsmMatch m₁ m₂) :
    m₁.evalNat urs = m₂.evalNat urs := by
  obtain ⟨hg, hw, hu, ho⟩ := h
  unfold Msm.evalNat
  rw [hg, hw, hu, (ho.map (fun t => t.1.val • t.2)).sum_eq]

/-- `MsmMatch` is decidable when the coefficients and terms are: this is the concrete check run against a
captured MSM (compare the `2 ^ k` g-scalars, the `w`/`u` scalars, and the term list). -/
instance {k : ℕ} {F G : Type*} [DecidableEq F] [DecidableEq G] (m₁ m₂ : Msm k F G) :
    Decidable (MsmMatch m₁ m₂) := by
  unfold MsmMatch; infer_instance

open MvPolynomial Finset Fintype in
/-- Soundness of the random-evaluation match (Schwartz–Zippel): if a coefficient of the assembled
MSM minus the captured one is a nonzero polynomial `p` in the proof scalars and challenges, a
uniformly random evaluation misses the mismatch with probability `≤ deg p / |F_p|`. `p` is left
abstract — *not* instantiated at `assemble`'s actual coefficients — so this is not yet a Lean link
from "one random proof" to assembly correctness (see the module note above). -/
theorem fingerprint_match_random_eval_sound {n : ℕ} {p : MvPolynomial (Fin n) Fp} (hp : p ≠ 0) :
    (#{f ∈ piFinset fun _ => (univ : Finset Fp) | eval f p = 0} : ℚ≥0)
        / (scalarFieldOrder : ℚ≥0) ^ n ≤ (p.totalDegree : ℚ≥0) / scalarFieldOrder :=
  fingerprint_schwartz_zippel hp

/-- The assembled MSM carries `2 ^ k` URS-generator coefficients (`gScalars : Fin (2 ^ k) → F`),
matching the captured Orchard fingerprint's `2 ^ 11 = 2048` g-scalars (`k = 11`). -/
theorem gScalars_card (k : ℕ) : Fintype.card (Fin (2 ^ k)) = 2 ^ k := Fintype.card_fin _

/-- The captured Orchard domain size: `k = 11` gives `2 ^ 11 = 2048` g-scalars. -/
theorem orchard_gScalars : (2 : ℕ) ^ 11 = 2048 := by norm_num

end Zcash.Snark
